/// Dev-harness mailbox and burst types for Trial 0 headless exchange.
///
/// Nothing in this module may appear in client-facing UI output. All trace events
/// use machine-event language only. Vocabulary labels (Active, Warm, Dormant,
/// Suspended, Severed, Burned) are absent until Stage H1 human gate passes.
///
/// DevMailboxId is a random 32-byte opaque token shared out-of-band between
/// sender and receiver. The relay stores bursts keyed by this token and cannot
/// link it to any identity key, session key, or payload content.

use crate::session::{FreshnessNonce, RouteId};
use crate::transcript::{FlashTranscriptV2, TransportKeyMaterial};
use rand_core::{OsRng, RngCore};
use scp_cryptography::{scp_derive_key, DomainLabel};
use scp_cryptography::keys::{x25519_dh, x25519_generate_keypair, CryptoError, SessionKey as CryptoSessionKey};
use scp_vitality::VitalityState;
use scp_wire_format::constants::{
    VITALITY_ACTIVE, VITALITY_BURNED, VITALITY_DORMANT,
    VITALITY_SEVERED, VITALITY_SUSPENDED, VITALITY_WARM,
};
use serde::{Deserialize, Serialize};

/// Opaque 32-byte mailbox routing token.
///
/// Generated by the receiver with `DevMailboxId::generate()` and shared with
/// the sender out-of-band. The relay sees only this token as a bucket key —
/// it cannot link it to any identity. Token is valid for the duration of a
/// dev-harness session (no automatic expiry at the relay level).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DevMailboxId(pub [u8; 32]);

impl DevMailboxId {
    pub fn generate() -> Self {
        let mut token = [0u8; 32];
        OsRng.fill_bytes(&mut token);
        Self(token)
    }

    pub fn to_hex(&self) -> String {
        hex_encode(&self.0)
    }

    pub fn from_hex(s: &str) -> Result<Self, HarnessError> {
        let bytes = hex_decode(s)?;
        if bytes.len() != 32 {
            return Err(HarnessError::InvalidMailboxId);
        }
        let mut arr = [0u8; 32];
        arr.copy_from_slice(&bytes);
        Ok(Self(arr))
    }
}

/// All receiver-side fields required to reconstruct the session key and decrypt.
///
/// Serialized as CBOR by the sender and stored opaquely at the relay.
/// The relay cannot read payload content — it only sees the outer DevMailboxId
/// used as a bucket key, plus the byte length of this struct.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DevHarnessBurst {
    /// Sender's X25519 ephemeral public key — receiver DH input.
    pub sender_ephemeral_pub: [u8; 32],
    /// Route ID committed to in the transcript hash.
    pub route_id: [u8; 16],
    /// Freshness nonce committed to in the transcript hash.
    pub freshness_nonce: u64,
    /// Vitality byte committed to in the transcript hash.
    pub vitality_byte: u8,
    /// ChaCha20-Poly1305 nonce used during encryption.
    /// Previously discarded (`_enc_nonce`) — must be retained for receiver decrypt.
    pub enc_nonce: [u8; 12],
    /// Encrypted payload including authentication tag.
    pub ciphertext: Vec<u8>,
}

impl DevHarnessBurst {
    pub fn route_id_hex(&self) -> String {
        hex_encode(&self.route_id)
    }
}

/// Serializes a `DevHarnessBurst` to CBOR bytes.
pub fn serialize_burst(burst: &DevHarnessBurst) -> Result<Vec<u8>, HarnessError> {
    serde_cbor::to_vec(burst).map_err(|_| HarnessError::SerializationFailed)
}

/// Deserializes a `DevHarnessBurst` from CBOR bytes.
pub fn deserialize_burst(bytes: &[u8]) -> Result<DevHarnessBurst, HarnessError> {
    serde_cbor::from_slice(bytes).map_err(|_| HarnessError::DeserializationFailed)
}

/// Decrypts a `DevHarnessBurst` using the recipient's handshake private key.
///
/// Reconstructs the session key via v2 bilateral DH path:
///   dh_output = X25519(recipient_handshake_priv, burst.sender_ephemeral_pub)
///   session_key = scp_derive_key(Transport, dh_output || transcript_v2_hash || recipient_ops_pub)
///   plaintext = ChaCha20-Poly1305.decrypt(ciphertext, enc_nonce)
///
/// Returns an error if the burst was encrypted with the v1 path (vitality byte
/// alone is not the discriminator — the caller must ensure v2 was used).
pub fn receive_harness(
    recipient_handshake_priv: &[u8; 32],
    recipient_ops_pub: &[u8; 32],
    burst: &DevHarnessBurst,
) -> Result<Vec<u8>, HarnessError> {
    let vitality = vitality_from_byte(burst.vitality_byte)?;

    let dh_output = x25519_dh(recipient_handshake_priv, &burst.sender_ephemeral_pub);

    let route_id = RouteId(burst.route_id);
    let nonce = FreshnessNonce(burst.freshness_nonce);

    let transcript = FlashTranscriptV2 {
        route_id,
        nonce,
        recipient_ops_pub: *recipient_ops_pub,
        vitality_snapshot: vitality,
        protocol_version: 2,
        sender_ephemeral_pub: burst.sender_ephemeral_pub,
    };
    let transcript_hash = transcript.hash();

    let key_material = TransportKeyMaterial {
        ephemeral_seed: dh_output,
        transcript_hash,
        recipient_binding: *recipient_ops_pub,
    };

    let session_key = CryptoSessionKey(scp_derive_key(DomainLabel::Transport, &key_material.as_bytes()));

    session_key
        .decrypt(&burst.ciphertext, &burst.enc_nonce)
        .map_err(|e: CryptoError| match e {
            CryptoError::DecryptionFailed => HarnessError::DecryptionFailed,
            CryptoError::InvalidKey => HarnessError::DecryptionFailed,
        })
}

/// Maps a vitality wire byte to a `VitalityState`.
///
/// Returns `HarnessError::UnknownVitalityByte` for any byte not in the wire-format
/// constants. Does not produce vocabulary labels in error output.
pub fn vitality_from_byte(byte: u8) -> Result<VitalityState, HarnessError> {
    match byte {
        b if b == VITALITY_ACTIVE    => Ok(VitalityState::Active),
        b if b == VITALITY_WARM      => Ok(VitalityState::Warm),
        b if b == VITALITY_DORMANT   => Ok(VitalityState::Dormant),
        b if b == VITALITY_SUSPENDED => Ok(VitalityState::Suspended),
        b if b == VITALITY_SEVERED   => Ok(VitalityState::Severed),
        b if b == VITALITY_BURNED    => Ok(VitalityState::Burned),
        other => Err(HarnessError::UnknownVitalityByte(other)),
    }
}

/// Maps a `VitalityState` to its wire byte. Used by the sender to populate `DevHarnessBurst`.
pub fn vitality_to_byte(state: &VitalityState) -> u8 {
    match state {
        VitalityState::Active    => VITALITY_ACTIVE,
        VitalityState::Warm      => VITALITY_WARM,
        VitalityState::Dormant   => VITALITY_DORMANT,
        VitalityState::Suspended => VITALITY_SUSPENDED,
        VitalityState::Severed   => VITALITY_SEVERED,
        VitalityState::Burned    => VITALITY_BURNED,
    }
}

/// Packages a [`DevHarnessBurst`] for relay-mailbox delivery without verifying
/// the recipient's handshake-key signature.
///
/// Use ONLY from the dev harness CLI (`scp-cli send`) where the recipient's
/// handshake pub is provided directly out-of-band. The full DH-based
/// cryptographic construction — X25519 key exchange, `scp_derive_key` session
/// key, ChaCha20-Poly1305 encryption — is identical to the verified path.
/// Only the handshake-key ops-signature check is omitted.
///
/// `recipient_ops_pub` is bound into the v2 transcript hash and **must** match
/// the value the recipient passes to `receive_harness()`.
pub fn send_harness_direct(
    recipient_ops_pub:    &[u8; 32],
    recipient_handshake_pub: &[u8; 32],
    payload: &[u8],
) -> DevHarnessBurst {
    let (sender_secret, sender_pub) = x25519_generate_keypair();
    let dh_output = x25519_dh(&sender_secret, recipient_handshake_pub);

    let route_id = RouteId::generate();
    let nonce    = FreshnessNonce::generate();
    let vitality = VitalityState::Active;

    let transcript = FlashTranscriptV2 {
        route_id:             route_id.clone(),
        nonce:                nonce.clone(),
        recipient_ops_pub:    *recipient_ops_pub,
        vitality_snapshot:    vitality.clone(),
        protocol_version:     2,
        sender_ephemeral_pub: sender_pub,
    };

    let key_material = TransportKeyMaterial {
        ephemeral_seed:    dh_output,
        transcript_hash:   transcript.hash(),
        recipient_binding: *recipient_ops_pub,
    };

    let session_key = CryptoSessionKey(scp_derive_key(DomainLabel::Transport, &key_material.as_bytes()));
    let (ciphertext, enc_nonce) = session_key.encrypt(payload);

    DevHarnessBurst {
        sender_ephemeral_pub: sender_pub,
        route_id:             route_id.0,
        freshness_nonce:      nonce.0,
        vitality_byte:        vitality_to_byte(&vitality),
        enc_nonce,
        ciphertext,
    }
}

/// Lowercase hex encode.
pub fn hex_encode(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{:02x}", b)).collect()
}

/// Lowercase hex decode.
pub fn hex_decode(s: &str) -> Result<Vec<u8>, HarnessError> {
    if s.len() % 2 != 0 {
        return Err(HarnessError::InvalidHex);
    }
    (0..s.len())
        .step_by(2)
        .map(|i| {
            u8::from_str_radix(&s[i..i + 2], 16).map_err(|_| HarnessError::InvalidHex)
        })
        .collect()
}

#[derive(Debug, thiserror::Error)]
pub enum HarnessError {
    #[error("decryption failed: authentication tag mismatch")]
    DecryptionFailed,
    #[error("CBOR serialization failed")]
    SerializationFailed,
    #[error("CBOR deserialization failed")]
    DeserializationFailed,
    #[error("unknown vitality byte: {0}")]
    UnknownVitalityByte(u8),
    #[error("invalid mailbox id: expected 32 hex bytes")]
    InvalidMailboxId,
    #[error("invalid hex string")]
    InvalidHex,
    #[error("v1 send path is not supported in the dev harness: publish a handshake ephemeral first")]
    V1PathNotSupported,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::transcript::TransportKeyMaterial;
    use scp_cryptography::keys::x25519_generate_keypair;
    use scp_cryptography::{scp_derive_key, DomainLabel};
    use scp_cryptography::keys::SessionKey as CryptoSessionKey;

    fn make_burst(
        sender_secret: &[u8; 32],
        sender_pub: &[u8; 32],
        recipient_handshake_pub: &[u8; 32],
        recipient_ops_pub: &[u8; 32],
        plaintext: &[u8],
    ) -> DevHarnessBurst {
        let dh_output = x25519_dh(sender_secret, recipient_handshake_pub);

        let route_id = RouteId([0x42u8; 16]);
        let nonce = FreshnessNonce(0xdeadbeef_cafebabe);
        let vitality = VitalityState::Active;

        let transcript = FlashTranscriptV2 {
            route_id: route_id.clone(),
            nonce: nonce.clone(),
            recipient_ops_pub: *recipient_ops_pub,
            vitality_snapshot: vitality.clone(),
            protocol_version: 2,
            sender_ephemeral_pub: *sender_pub,
        };
        let transcript_hash = transcript.hash();

        let key_material = TransportKeyMaterial {
            ephemeral_seed: dh_output,
            transcript_hash,
            recipient_binding: *recipient_ops_pub,
        };

        let session_key = CryptoSessionKey(scp_derive_key(DomainLabel::Transport, &key_material.as_bytes()));
        let (ciphertext, enc_nonce) = session_key.encrypt(plaintext);

        DevHarnessBurst {
            sender_ephemeral_pub: *sender_pub,
            route_id: route_id.0,
            freshness_nonce: nonce.0,
            vitality_byte: vitality_to_byte(&vitality),
            enc_nonce,
            ciphertext,
        }
    }

    #[test]
    fn round_trip_encrypt_decrypt() {
        let (sender_secret, sender_pub) = x25519_generate_keypair();
        let (recipient_secret, recipient_pub) = x25519_generate_keypair();
        let ops_pub = [0x11u8; 32];

        let plaintext = b"hello scp";
        let burst = make_burst(&sender_secret, &sender_pub, &recipient_pub, &ops_pub, plaintext);

        let recovered = receive_harness(&recipient_secret, &ops_pub, &burst).unwrap();
        assert_eq!(recovered, plaintext);
    }

    #[test]
    fn wrong_recipient_key_fails() {
        let (sender_secret, sender_pub) = x25519_generate_keypair();
        let (_recipient_secret, recipient_pub) = x25519_generate_keypair();
        let (wrong_secret, _) = x25519_generate_keypair();
        let ops_pub = [0x11u8; 32];

        let burst = make_burst(&sender_secret, &sender_pub, &recipient_pub, &ops_pub, b"data");

        assert!(matches!(
            receive_harness(&wrong_secret, &ops_pub, &burst),
            Err(HarnessError::DecryptionFailed)
        ));
    }

    #[test]
    fn wrong_ops_pub_fails() {
        let (sender_secret, sender_pub) = x25519_generate_keypair();
        let (recipient_secret, recipient_pub) = x25519_generate_keypair();
        let ops_pub = [0x11u8; 32];
        let wrong_ops_pub = [0x22u8; 32];

        let burst = make_burst(&sender_secret, &sender_pub, &recipient_pub, &ops_pub, b"data");

        assert!(matches!(
            receive_harness(&recipient_secret, &wrong_ops_pub, &burst),
            Err(HarnessError::DecryptionFailed)
        ));
    }

    #[test]
    fn cbor_serialization_round_trip() {
        let (sender_secret, sender_pub) = x25519_generate_keypair();
        let (recipient_secret, recipient_pub) = x25519_generate_keypair();
        let ops_pub = [0x11u8; 32];

        let burst = make_burst(&sender_secret, &sender_pub, &recipient_pub, &ops_pub, b"cbor test");
        let bytes = serialize_burst(&burst).unwrap();
        let recovered_burst = deserialize_burst(&bytes).unwrap();

        let plaintext = receive_harness(&recipient_secret, &ops_pub, &recovered_burst).unwrap();
        assert_eq!(plaintext, b"cbor test");
    }

    #[test]
    fn mailbox_id_hex_round_trip() {
        let id = DevMailboxId::generate();
        let hex = id.to_hex();
        assert_eq!(hex.len(), 64);
        let recovered = DevMailboxId::from_hex(&hex).unwrap();
        assert_eq!(id, recovered);
    }

    #[test]
    fn mailbox_id_from_hex_rejects_wrong_length() {
        assert!(matches!(
            DevMailboxId::from_hex("deadbeef"),
            Err(HarnessError::InvalidMailboxId)
        ));
    }

    #[test]
    fn hex_encode_decode_round_trip() {
        let data = [0xde, 0xad, 0xbe, 0xef, 0x00, 0xff];
        let hex = hex_encode(&data);
        assert_eq!(hex, "deadbeef00ff");
        let back = hex_decode(&hex).unwrap();
        assert_eq!(back, data);
    }

    #[test]
    fn vitality_byte_round_trip() {
        for (state, expected_byte) in [
            (VitalityState::Active, VITALITY_ACTIVE),
            (VitalityState::Warm, VITALITY_WARM),
            (VitalityState::Dormant, VITALITY_DORMANT),
            (VitalityState::Suspended, VITALITY_SUSPENDED),
            (VitalityState::Severed, VITALITY_SEVERED),
            (VitalityState::Burned, VITALITY_BURNED),
        ] {
            let byte = vitality_to_byte(&state);
            assert_eq!(byte, expected_byte);
            let recovered = vitality_from_byte(byte).unwrap();
            assert_eq!(recovered, state);
        }
    }

    #[test]
    fn unknown_vitality_byte_returns_error() {
        assert!(matches!(
            vitality_from_byte(0xFF),
            Err(HarnessError::UnknownVitalityByte(0xFF))
        ));
    }
}
